run:
  skip-files:
    - ".*test\\.go$"

linters:
  # Enable all available linters.
  # Default: false
  enable-all: true
  # Disable specific linter
  # https://golangci-lint.run/usage/linters/#disabled-by-default
  disable:
    - varcheck
    - maligned
    - golint
    - structcheck
    - ifshort
    - nosnakecase
    - scopelint
    - interfacer
    - exhaustivestruct
    - deadcode
    - gci
    - gofumpt
    - depguard
    - wrapcheck
    - containedctx
    - errorlint